package edu.iastate.cs228.hw3;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *  
 * @author Shivkarthi Sundar
 *
 */

public class PuzzleSolver {
	/**
	 *  Read an initial state from an file.  Solve the eight puzzle using two heuristics based on 
	 *  the number of mismatched tiles and the Manhattan distance.  Each solution is printed out 
	 *  as a sequence of states, generated by single moves, from the initial state to the goal
	 *  state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException {
		String s = "\"2012\",\"Alabama\",\"14\",\"97\"";
		String s1 = "\"year\",,\"state\",";
		Scanner scan = new Scanner(s);
		Scanner scan2 = new Scanner(s1);
		System.out.println(s);
		System.out.println(s1);
		scan.useDelimiter(",");
		scan2.useDelimiter(",");
		ArrayList<String> als = new ArrayList<String>();
		while (scan2.hasNext()) {
			als.add(scan2.next());
		}

		for (int x = 0; x < als.size(); x++) {
			System.out.println(als.get(x));
		}
		//		System.out.println('a'-'0');
		//		System.out.println('"' - '0');
		//		State initialState = new State(args[0]);
		//		System.out.println(EightPuzzle.solve8Puzzle(initialState));
	}
}
